"""ajout des colonnes de visualisation

Revision ID: 5afe0fcc4f08
Revises: 
Create Date: 2025-07-13 06:05:59.038584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afe0fcc4f08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confusion_matrix', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('roc_curve', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('regression_plot', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feature_importance', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preview_data', sa.Text(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('regression_plot_path')
        batch_op.drop_column('feature_importance_path')
        batch_op.drop_column('confusion_matrix_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confusion_matrix_path', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('feature_importance_path', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('regression_plot_path', sa.VARCHAR(length=300), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('preview_data')
        batch_op.drop_column('feature_importance')
        batch_op.drop_column('regression_plot')
        batch_op.drop_column('roc_curve')
        batch_op.drop_column('confusion_matrix')

    # ### end Alembic commands ###
